### ISSUE TITLE
Write a script for plagiarism detection

### ISSUE THREAD

**Issue by rdragos** [infoclock/OlympicTracker#13]
This can be decoupled with the website. Just take the most recent submissions for each user and run it through this: http://theory.stanford.edu/~aiken/moss/

I think this doesn't require lots of effort in understanding current code base, mainly because the sources are saved for each user in a specific folder and corresponding source name. The difficulty resides in putting back the results.

**Comment by palcu** [comment]
Asta o băgăm manual. Or să fie puține foldere de evaluat.
